from enum import IntEnum, Enum


class Role(str, Enum):
    ADMIN = "admin"
    MODERATOR = "moderator"
    USER = "user"


class Conversation(IntEnum):
    INPUT_NAME = 1
    INPUT_EMAIL = 2
    CONFIRM_PROFILE = 3
    WAITING_ADMIN_PASSWORD = 4
    WAITING_EVENT_NAME = 5
    WAITING_EVENT_DATETIME = 6
    WAITING_EVENT_DESC = 7
    WAITING_EVENT_SEATS = 8
    WAITING_BROADCAST_MESSAGE = 9
    WAITING_BROADCAST_CONFIRM = 10
    WAITING_EVENT_BROADCAST_MESSAGE = 11
    WAITING_EVENT_BROADCAST_CONFIRM = 12
    EDIT_CONTENT_KEY = 13
    EDIT_CONTENT_TITLE = 14
    EDIT_CONTENT_BODY = 15
    EDIT_MENU_ITEM = 16
    EDIT_TEMPLATE = 17
    EDIT_EVENT_SELECT = 18
    EDIT_EVENT_FIELD = 19
    EDIT_EVENT_VALUE = 20
    ROLE_ASSIGN_USER = 21
    ROLE_ASSIGN_VALUE = 22

